namespace SMTRandoApp.Modeling;

internal record Race(int ID, string JapaneseName, string EnglishName, string RomajiName) {

	public static readonly Race[] VanillaRaces = {
		new(0x00, "マジン", "Deity", "Majin"),
		new(0x01, "メガミ", "Megami", "Megami"),
		new(0x02, "テンマ", "Tenma", "Tenma"),
		new(0x03, "キシン", "Noble", "Kishin"),
		new(0x04, "セラフ", "Seraph", "Seraph"),
		new(0x05, "テンシ", "Angel", "Tenshi"),
		new(0x06, "リュウジン", "Dragon", "Ryujin"),
		new(0x07, "レイチョウ", "Apex", "Reicho"),
		new(0x08, "シンジュウ", "Avatar", "Shinju"),
		new(0x09, "セイジュウ", "Sacred", "Seijuu"),
		new(0x0A, "セイレイ", "Primal", "Seirei"),
		new(0x0B, "キジョ", "Femme", "Kijo"),
		new(0x0C, "ヨウマ", "Ghoul", "Youma"),
		new(0x0D, "ヤマ", "Night", "Yama"),
		new(0x0E, "ヨウセイ", "Fairy", "Yousei"),
		new(0x0F, "ダテンシ", "Fallen", "Datens"),
		new(0x10, "リュウオウ", "Snake", "Ryuoo"),
		new(0x11, "ヨウチョウ", "Flight", "Youcho"),
		new(0x12, "マジュウ", "Beast", "Majuu"),
		new(0x13, "トウキ", "Touki", "Touki"),
		new(0x14, "ヨウキ", "Brute", "Youki"),
		new(0x15, "チレイ", "Guard", "Jirae"),
		new(0x16, "ジュウジン", "Theria", "Juujin"),
		new(0x17, "メシアキョウト", "Law", "Mesian"),
		new(0x18, "ガイアキョウト", "Chaos", "Gaian"),
		new(0x19, "ジャシン", "Vile", "Jashin"),
		new(0x1A, "マオウ", "Tyrant", "Maou"),
		new(0x1B, "ジャリュウ", "Drake", "Jaryuu"),
		new(0x1C, "キョウチョウ", "Raptor", "Kyocho"),
		new(0x1D, "ヨウジュウ", "Wilder", "Youjuu"),
		new(0x1E, "ジャキ", "Wicked", "Jaki"),
		new(0x1F, "ユウキ", "Haunt", "Yuuki"),
		new(0x20, "アクリョウ", "Spirit", "Akuryo"),
		new(0x21, "シキ", "Undead", "Shiki"),
		new(0x22, "ゲドウ", "Foul", "Gedou"),
		new(0x23, "マシン", "Robot", "Mashin"),
		new(0x24, "イヌ", "Canine", "Inu"),
		new(0x25, "チョウジン", "Avian", "Chojin"),
		new(0x26, "ケン", "Sword", "Ken"),
	};

	internal static readonly string[] RelatableClasses = new string[] {
		"??????",
		"￥1000",
		"Actor",
		"Addict",
		"Admin",
		"Agent",
		"Aide",
		"Alien",
		"Amigo",
		"Anchor",
		"Angler",
		"Artist",
		"BFF",
		"Baker",
		"Bandit",
		"Barfly",
		"Beauty",
		"Bigot",
		"Bishop",
		"Boomer",
		"Boover",
		"Boss",
		"Bowler",
		"Boxer",
		"Buddy",
		"Bully",
		"CEO",
		"Caddie",
		"Carnie",
		"Cheese",
		"Chef",
		"Chief",
		"Child",
		"Chump",
		"Clerk",
		"Clown",
		"Coach",
		"Cohort",
		"Cousin",
		"Coward",
		"Creep",
		"Critic",
		"Crony",
		"Crook",
		"Dancer",
		"Deacon",
		"Dean",
		"Demon",
		"Deputy",
		"Despot",
		"Dimwit",
		"Dingus",
		"Diva",
		"Diver",
		"Doctor",
		"Dork",
		"Driver",
		"Dunce",
		"Dweeb",
		"Editor",
		"Elder",
		"Eloper",
		"Emoji",
		"Enemy",
		"Error",
		"Expert",
		"Extra",
		"Faker",
		"Farmer",
		"Felon",
		"Fifer",
		"Fig",
		"Fisher",
		"Floozy",
		"Fogram",
		"Foodie",
		"Fool",
		"Fraud",
		"Freak",
		"Friend",
		"Furry",
		"Gamer",
		"Geek",
		"Genius",
		"Gerudo",
		"Gigolo",
		"Golfer",
		"Goober",
		"Goon",
		"Goonie",
		"Gossip",
		"Gunner",
		"Gyaru",
		"Hacker",
		"Harlot",
		"Hater",
		"Hermit",
		"Hero",
		"Hippie",
		"Hobo",
		"Hooker",
		"Hunter",
		"Hylian",
		"Idol",
		"Inbred",
		"Inmate",
		"Intern",
		"Jailer",
		"Jerk",
		"Jester",
		"Jockey",
		"Jogger",
		"Joker",
		"Judge",
		"Junkie",
		"Junior",
		"Juror",
		"Juvie",
		"Kicker",
		"Killer",
		"Klutz",
		"Knave",
		"Knight",
		"Lamer",
		"Lawyer",
		"Leader",
		"Lecher",
		"Legend",
		"Leper",
		"Liar",
		"Lizard",
		"Local",
		"Loli",
		"Loner",
		"Loser",
		"Lurker",
		"Maniac",
		"Martyr",
		"Master",
		"Mayor",
		"Meanie",
		"Medic",
		"Medium",
		"Menace",
		"Mentor",
		"Miser",
		"Misfit",
		"Model",
		"Monk",
		"Moron",
		"Mortal",
		"Muse",
		"Mutant",
		"Nanny",
		"Narc",
		"NEET",
		"Nerd",
		"Nimrod",
		"Ninja",
		"Nitwit",
		"Nobody",
		"Notary",
		"Novice",
		"NPC",
		"Nudist",
		"Numpty",
		"Nurse",
		"Oaf",
		"OB/GYN",
		"Oracle",
		"Orator",
		"Orphan",
		"Outlaw",
		"Padre",
		"Parent",
		"Pariah",
		"Patron",
		"Patsy",
		"Pedant",
		"Perv",
		"Pet",
		"Phony",
		"Pilot",
		"Pirate",
		"Player",
		"Poet",
		"Pooper",
		"Priest",
		"Pundit",
		"Punk",
		"Puppet",
		"Rabbi",
		"Racer",
		"Random",
		"Ranger",
		"Rapper",
		"Rascal",
		"Regent",
		"Rider",
		"Rival",
		"Roadie",
		"Rocker",
		"Rogue",
		"Rookie",
		"Rugrat",
		"Sadist",
		"Sage",
		"Savant",
		"Scout",
		"Senpai",
		"Sensei",
		"Sherpa",
		"Sicko",
		"Singer",
		"Skank",
		"Skater",
		"Slouch",
		"Slut",
		"Smoker",
		"Sniper",
		"Spouse",
		"Spy",
		"Stoner",
		"Stoop",
		"Stooge",
		"Sucker",
		"Suitor",
		"Sultan",
		"Teen",
		"Tenant",
		"Thief",
		"Titan",
		"Trader",
		"Troop",
		"Tutor",
		"Twerp",
		"Tycoon",
		"Ugly",
		"Umpire",
		"Uwasa",
		"Valet",
		"Vegan",
		"Vendor",
		"Victim",
		"Viewer",
		"Viking",
		"VIP",
		"Virgin",
		"Voter",
		"Voyeur",
		"Waifu",
		"Warden",
		"Weeb",
		"Weenie",
		"Weirdo",
		"Wimp",
		"Who?",
		"Witch",
		"Wizard",
		"Wretch",
		"Writer",
		"Wussie",
		"Yankee",
		"Yeoman",
		"Youkai",
	};
}
