namespace SMTRandoApp.Randomization;

partial class DemonShuffler {
	private static readonly string[] RelatableNamesF = new string[] {
		"Abigail",
		"Agatha",
		"Alana",
		"Alice",
		"Amanda",
		"Amani",
		"Angela",
		"April",
		"Astrid",
		"Audrey",
		"Babs",
		"Bebe",
		"Becky",
		"Betsy",
		"Bexley",
		"Bonnie",
		"Brandy",
		"Britney",
		"Brooke",
		"Carly",
		"Carrie",
		"Celine",
		"Chiaki",
		"Chitose",
		"Claire",
		"Clarice",
		"Connie",
		"Courtney",
		"Cynthia",
		"Daisy",
		"Dakota",
		"Daphne",
		"Deborah",
		"Delilah",
		"Denice",
		"Diana",
		"Diana",
		"Dolly",
		"Dorothy",
		"Edith",
		"Eiliyah",
		"Elaine",
		"Elisha",
		"Eloise",
		"Emily",
		"Erica",
		"Esther",
		"Etna",
		"Evelyn",
		"Faren",
		"Farrah",
		"Fatima",
		"Federica",
		"Felicity",
		"Fernanda",
		"Fifi",
		"Fiona",
		"Franny",
		"Frieda",
		"Gabi",
		"Gertrud",
		"Gianni",
		"Gina",
		"Ginger",
		"Gladys",
		"Gloria",
		"Gracie",
		"Gretchen",
		"Gwen",
		"Hailey",
		"Hannah",
		"Harriet",
		"Hazel",
		"Heidi",
		"Helen",
		"Helga",
		"Hilda",
		"Hinata",
		"Holly",
		"Imani",
		"Ingrid",
		"Irene",
		"Irma",
		"Isis",
		"Ivy",
		"Jackie",
		"Janet",
		"Janine",
		"Jezebel",
		"Johanna",
		"Josie",
		"Joy",
		"Judy",
		"Juliet",
		"Juniper",
		"Kate",
		"Katrina",
		"Kelly",
		"Kendal",
		"Kiki",
		"Kirstie",
		"Lauretta",
		"Leticia",
		"Liah",
		"Lila",
		"Linda",
		"Liz",
		"Lorelei",
		"Lorrie",
		"Luanne",
		"Lucille",
		"Maggie",
		"Makoto",
		"Mandy",
		"Martha",
		"Mary",
		"Melinda",
		"Melissa",
		"Mindy",
		"Miriam",
		"Momo",
		"Nadia",
		"Nagisa",
		"Nanako",
		"Nancy",
		"Naomi",
		"Natalie",
		"Natsumi",
		"Nene",
		"Nicole",
		"Nora",
		"Olga",
		"Ophelia",
		"Oprah",
		"Orit",
		"Ornella",
		"Paulina",
		"Peggy",
		"Penelope",
		"Peppa",
		"Phyllis",
		"Polly",
		"Rachel",
		"Raven",
		"Rebecca",
		"Reece",
		"Regina",
		"Rhonda",
		"Risa",
		"Robin",
		"Roka",
		"Rosaline",
		"Sally",
		"Sasha",
		"Selena",
		"Selma",
		"Sharona",
		"Shiki",
		"Sophie",
		"Stacy",
		"Susie",
		"Suzu",
		"Svetlana",
		"Tabitha",
		"Tamara",
		"Tanya",
		"Tatiana",
		"Teresa",
		"Tess",
		"Thelma",
		"Tina",
		"Tomoko",
		"Tracy",
		"Trisha",
		"Uliana",
		"Uma",
		"Umi",
		"Ursula",
		"Uta",
		"Valerie",
		"Vanessa",
		"Vanna",
		"Velma",
		"Veronica",
		"Vesta",
		"Victoria",
		"Viera",
		"Violette",
		"Vivian",
		"Wanda",
		"Wendy",
		"Whitney",
		"Willow",
		"Wilma",
		"Xoan",
		"Yael",
		"Yasmin",
		"Ymir",
		"Yukiko",
		"Yurine",
		"Yvette",
		"Zadie",
		"Zelda",
		"Zoey",
		"Zulma",
	};

	private static readonly string[] RelatableNamesM = new string[] {
		"Aaron",
		"Abdul",
		"Abraham",
		"Adam",
		"Agahnim",
		"Ahmed",
		"Albert",
		"Anthony",
		"Arnold",
		"Ashton",
		"Barney",
		"Bart",
		"Bashir",
		"Baxter",
		"Bentley",
		"Billy",
		"Brady",
		"Brent",
		"Brian",
		"Buck",
		"Caleb",
		"Calvin",
		"Carlos",
		"Casper",
		"Cedric",
		"Charlie",
		"Christos",
		"Clint",
		"Cooper",
		"Craig",
		"Daisuke",
		"Daniel",
		"Derek",
		"Devin",
		"Dexter",
		"Dorian",
		"Drake",
		"Dudley",
		"Dwayne",
		"Dwight",
		"Earl",
		"Edward",
		"Elijah",
		"Elvis",
		"Emmett",
		"Erwin",
		"Eugene",
		"Eustace",
		"Evan",
		"Ezekiel",
		"Fabio",
		"Falco",
		"Fausto",
		"Felton",
		"Fidel",
		"Fitz",
		"Fletcher",
		"Flint",
		"Frank",
		"Fred",
		"Gary",
		"Gavin",
		"Georgie",
		"Gerard",
		"Gilbert",
		"Giovanni",
		"Giuseppe",
		"Greg",
		"Gunther",
		"Gustav",
		"Hamza",
		"Harold",
		"Harvey",
		"Hector",
		"Henry",
		"Hermes",
		"Hiroshi",
		"Horacio",
		"Hubert",
		"Hugh",
		"Ian",
		"Ichiro",
		"Iggy",
		"Ignazio",
		"Immanuel",
		"Isaac",
		"Ishmael",
		"Jack",
		"Jamal",
		"Jaxon",
		"Jebediah",
		"Jerome",
		"Jesse",
		"Jethro",
		"Jimmy",
		"Job",
		"Jonah",
		"Jose",
		"Kaname",
		"Karl",
		"Keith",
		"Kenji",
		"Kent",
		"Kevin",
		"Kirby",
		"Koji",
		"Langdon",
		"Larry",
		"Lars",
		"Lenny",
		"Lester",
		"Levi",
		"Lorenzo",
		"Luigi",
		"Luis",
		"Luke",
		"Marco",
		"Mario",
		"Marvin",
		"Mattias",
		"Maxwell",
		"Melvin",
		"Miguel",
		"Mike",
		"Morgan",
		"Mortimer",
		"Nasir",
		"Nauris",
		"Ned",
		"Neil",
		"Nick",
		"Niles",
		"Noah",
		"Nolan",
		"Norman",
		"Oswald",
		"Otis",
		"Otto",
		"Owen",
		"Ozzy",
		"Parker",
		"Pedro",
		"Phil",
		"Phineas",
		"Pierre",
		"Pierre",
		"Po",
		"Preston",
		"Quentin",
		"Ralph",
		"Raul",
		"Raymond",
		"Reginald",
		"Reuben",
		"Richard",
		"Roark",
		"Ronald",
		"Rosco",
		"Rudy",
		"Sal",
		"Sandro",
		"Sergio",
		"Seymour",
		"Shaq",
		"Shiloh",
		"Simon",
		"Stan",
		"Stewart",
		"Sven",
		"Takeshi",
		"Tanner",
		"Thomas",
		"Timothy",
		"Tobias",
		"Topher",
		"Trevor",
		"Troy",
		"Tucker",
		"Tyrone",
		"Ukyo",
		"Ulrich",
		"Ulysses",
		"Vance",
		"Victor",
		"Vincent",
		"Vito",
		"Vladimir",
		"Waldo",
		"Wallace",
		"Walter",
		"Wayne",
		"Wesley",
		"Wolfgang",
		"Woodrow",
		"Wyatt",
		"Yakov",
		"Yogi",
		"Yoshi",
		"Yuichiro",
		"Yuri",
		"Yuzu",
		"Zachary",
		"Zeke",
		"Zenji",
		"Ziggy",
	};

	private static readonly string[] RelatableNamesR = new string[] {
		"386SX-25",
		"Amiga500",
		"Apple II",
		"Atari800",
		"B128-80",
		"C128D",
		"C-3PO",
		"C64",
		"CBM 610",
		"Coleco",
		"CWD-4002",
		"Cybiko",
		"DAC-612",
		"DeepBlue",
		"Famicom",
		"Fridge",
		"Gamecube",
		"HAL 9000",
		"IBM PCjr",
		"Indigo2",
		"KoalaPad",
		"Laser XT",
		"Lisa 2",
		"MBC-775",
		"MPS1200",
		"Nintendo",
		"NWS-800",
		"NX-2420",
		"Osborne1",
		"PC-8801",
		"PET 2001",
		"Plus/4",
		"Potato",
		"PS/2 486",
		"R2-D2",
		"SC-55ST",
		"Sharp X1",
		"SNES",
		"Tandy",
		"ThinkPad",
		"TI-83",
		"TI-84SE",
		"TI-99/4A",
		"Toaster",
		"TRS-80",
		"V-GINY",
		"VIC-20",
		"Watson",
		"XBox 360",
		"XT-286",
		"Z-171",
		"ZX81",
	};


	private static readonly string[] CheeseNames = new string[] {
		"Abertam", "Acapella", "Ackawi", "Adelost", "Aggiano", "Airag", "Airedale", "Alverca", "Amalthee", "Ambert",
		"Amou", "Anari", "Anster", "Aradalen", "Aragon", "Ardrahan", "Asadero", "Asiago", "Assa", "Autun", "Azeitao",
		"Babybel", "Bad Axe", "Baladi", "Balaton", "Balfour", "Baluchon", "Bandal", "Barberey",
		"Bartlett", "Basajo", "Baserri", "Basing", "Baskeriu", "Batzos", "Baylough", "Beaufort", "Beaumont", "Bergader", "Bergues",
		"Bianca", "Bianco", "Bierkase", "Bijou", "Bismark", "Blarney", "Blenda", "Bleubry", "Blu '61", "Blue", "Bonifaz",
		"Bossa", "Bosworth", "Bougon", "Boursin", "Bouyssou", "Brie", "Brin", "Briscola", "Broccio",
		"Brocciu", "Broncha", "Brunost", "Bryndza", "Bucheret", "Bufalino", "Bufarolo", "Burgos", "Burrata", "Butte", "Byaslag",
		"Cabecou", "Caboc", "Cabrales", "Caciotta", "Calcagno", "Campfire", "Campi", "Cantal", "Caprano",
		"Capriago", "Caprice", "Capriny", "Caprotto", "Caravane", "Cardo", "Carlina", "Carlow", "Carmody", "Casatica", "Catupiry",
		"Cerney", "Chaource", "Chaumes", "Chavroux", "Cheddar", "Cheshire", "Chevre", "Chevres", "Chhurpi", "Cinerino", "Cirrus",
		"Civray", "Clonmore", "Coalho", "Cojack", "Colby", "Comte", "Comtomme", "Condio", "Coolea", "Cooleney", "Corleggy",
		"Cotija", "Cotswold", "Coupole", "CreMonte", "CreNoble", "Cremet", "Cremont", "Criffel", "Croghan", "Crottin", "Crowdie",
		"Crowley", "Crozier", "Cuajada", "Cubetto", "Curd",
		"Danbo", "Danby", "Dante", "Dauphin", "Derby", "Di.Vino", "Doolin", "Dorblu", "Dore-Mi", "Dorset",
		"Dorstone", "Doublet", "Drommen", "Dry Jack", "Dubliner", "Dunbarra", "Dunlop", "Dura", "Durrus",
		"Edam", "Edelpilz", "Edith", "Emlett", "Emmental", "Esrom", "Etorki",
		"Fermiere", "Feta", "Ficaccio", "Figaro", "Figue", "Filetta", "Finn", "Folded", "Fontal",
		"Fontiago", "Fontina", "Forme'", "Fougerus", "Friesago", "Friesian", "Friesla", "Frinault", "Fromage", "Fynbo",
		"Galbani", "Gamoneu", "Garrotxa", "Geitost", "Gjetost", "Gouda", "Goutu", "Gowrie", "Goya",
		"Grabetto", "Graddost", "Gran Bu", "Grana", "Graviera", "Grayson", "Greuilh", "Greve", "Grey Owl", "Gruyere", "Gubbeen",
		"Hafod", "Halloumi", "Hannah", "Harbison", "Harvest", "Havarti", "Havilah", "Hayloft", "Herve", "Hipi Iti",
		"Iberico", "Isabirra",
		"Kabritt", "Kanafeh", "Kaseri", "Kashar", "Kashta", "Kasseri", "Kenafa", "Kenne", "Kernhem", "Kiri", "Kummin",
		"La Peral", "La Tur", "Labneh", "Laguiole", "Lajta", "Landaff", "Langres", "Lappi", "Largo", "Laruns",
		"Le Brin", "Le Roule", "Leafield", "Lebbene", "Legato", "Leyden", "Lil Moo", "Lindale", "Liptauer", "Livarot",
		"Longhorn", "Lunetta", "Lyonnais",
		"Maasdam", "Madrona", "Magna", "Mahon", "Majorero", "Malvern", "Manchego", "Mandolin", "Manon", "Manouri",
		"Manteca", "Manur", "Margot", "Margotin", "Maribo", "Marisa", "Mascares", "Matocq", "McLaren", "Meira", "Melange",
		"Melville", "Menage", "Menonita", "Mesost", "Mettowee", "Mi-Ewe", "Miette", "Milleens", "Minuet", "Mixte", "Mobay",
		"Molbo", "Mona", "Mondseer", "Monet", "Montasio", "Monteo", "Moonglo", "Morbier", "Morcella", "Morgan",
		"Morlacco", "Mt Scott", "Mt Tam", "Muenster", "Muffato", "Mun-chee", "Munster", "Murol", "Mycella", "Myzithra",
		"Naboulsi", "Nantais", "New Moon", "Niolo", "Nocciolo", "Nocturne", "Noyan",
		"Oaxaca", "Old Ford", "Old Goat", "Oma", "Operetta", "Opus 42", "Orla", "Oscypek",
		"Paneer", "Panela", "Paniolo", "Parmesan", "Parrano", "Pastoral", "Pawlet", "Pecorino", "Penbryn", "PepBert",
		"Pepato", "Perroche", "Petida", "Phoebe", "Piave", "Picolo", "Pimento", "Piora", "Pizy", "Pokolbin", "Pompeii",
		"Postel", "Pourly", "Prastost", "Pressato", "Provel", "Pule", "Pyramide",
		"Rabacal", "Raclette", "Ragstone", "Ragusano", "Raschera", "Red Hawk", "Remedou", "Requeson", "Reverie", "Rheba",
		"Ricotta", "Ridder", "Rigotte", "Ringwell", "Rollot", "Romano", "Roncal", "Rondo", "Rosso", "Roule", "Roumy",
		"Rubens", "Rubi", "Rustinu",
		"Salers", "Samso", "Sancerre", "Sap Sago", "Saporito", "Sardo", "Sbrinz", "Sbronzo", "Scamorza",
		"Schloss", "Seahive", "Seastack", "Selva", "Serat", "Sharpam", "Sharpham", "Shepsog", "Siltcoos", "Siraz",
		"Sirene", "Snowdrop", "Sosha", "Spenwood", "Speziato", "Stawley",
		"Stilton", "String", "Sulguni", "Sunlight", "Swag", "Swiss",
		"Takelma", "Tala", "Taleggio", "Tamie", "Tango", "Tapas", "TeaHive", "Tegan", "Teifi", "Telemea",
		"Teneri", "Testouri", "Tetilla", "Tibet", "Tilsit", "Toma", "Tomme", "Tozzetto", "Trelawny", "Tronchon",
		"Truffe", "Tuada", "Tunworth", "Tupi", "Turunmaa", "Txiki", "Tymsboro", "Tyn Grug", "Tyning",
		"Ubriaco", "Ulloa", "Urda",
		"Vacherin", "Valencay", "Venaco", "Veneto", "Venus", "Vera", "Vesuvius", "Victoria", "Vigneron", "Vignotte",
		"Waterloo", "Wigmore",
		"Xynotyro",
		"Yeo Lake",
		"Zamorano", "Zimbro", "Zwitser",
	};
}
